site_name: VTA Python Book
theme:
  name: material
  language: ja
  custom_dir: overrides
  logo_icon: assets/black-logo.svg
  favicon: assets/favicon.jpg
  font:
    text: Noto Sans JP
    code: Roboto Mono
  features:
    - search.highlight
    - search.share
  plugins:
    - search:
        lang:
          - ja
          - en
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: white
      scheme: default
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      accent: light green
      toggle:
        icon: material/weather-night
        name: Switch to light mode
markdown_extensions:
  - meta
  - tables
  - def_list
  - footnotes
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra:
  disqus: vta-python-book
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - はじめに: index.md
  - Python基礎:
      - 1.0. Pythonなどのプログラミングの世界: chapter-1/python-world.md