site_name: VTA Python Book
site_description: 'テックフォードアカデミー1年生で学ぶ事を復習'
site_author: 'Heitor Hiorse'
site_url: 'https://docs.hekuta.net/'
repo_url: https://github.com/HEKUCHAN/VTA-Python-Book/
repo_name: HEKUCHAN/VTA-Python-Book

copyright: 'Copyright &copy; 2022 Heitor Hirose'

theme:
  name: material
  language: ja
  custom_dir: overrides
  logo_icon: assets/black-logo.svg
  favicon: assets/favicon.jpg
  font:
    text: Noto Sans JP
    code: Roboto Mono
  features:
    - search.highlight
    - search.share
  plugins:
    - tags
    - privacy
    - search:
        lang:
          - ja
          - en
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: white
      scheme: default
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      accent: light green
      toggle:
        icon: material/weather-night
        name: Switch to light mode
markdown_extensions:
  - meta
  - tables
  - def_list
  - footnotes
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - toc:
      permalink: "#"
      separator: "-"
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_css:
  - stylesheets/extra.css
extra:
  disqus: vta-python-book
  social:
    - icon: material/web
      link: https://greater-heitor.ssl-lolipop.jp/
    - icon: material/email
      link: mailto:Heitorhirose@gmail.com
    - icon: fontawesome/brands/github
      link: https://github.com/HEKUCHAN
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Heitor_Hirose
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/hirose_heitor/
  pages:
    - name: "プライバシーポリシー 免責事項"
      link: "/privacy-policy"
extra_javascript:
  - javascripts/mathjax.js
  - javascripts/shortcuts.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - はじめに: index.md
  - Python基礎:
    - Pythonなどのプログラミングの世界: chapter-1/python-world.md
    - Pythonのインストール:
      - Pythonインストール MacOS: chapter-1/macos-install.md
      - Pythonインストール Windows10: chapter-1/windows-install.md
    - Pythonのインタプリタで遊んでみよう: chapter-1/interpreter.md
    - おすすめのファイル管理方法: chapter-1/how-to-save-files.md
    - ターミナルの扱い方を学ぼう: chapter-1/how-to-use-terminal.md
    - 変数とデータ型: chapter-1/python-variable.md
    - 文字列型 - String: chapter-1/python-string.md
    - 整数型 - Int: chapter-1/python-int.md
    - 配列型 - List: chapter-1/python-list.md
  - 競技プログラミング Python:
    - Pythonで競プロ: competitive/competitive-python.md
    - Tips:
      - 内包表記: competitive/tips/competitive-list-comprehensions.md
