version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:latest
      - image: circleci/python:3.9.6-buster
    steps:
      - checkout
  deploy:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "${KEY_FINGERPRINT}"
      - run:
          name: SSH
          command: ssh ${USER_NAME}@${HOST_NAME} 'cd /var/www/VTA-Python-Book/ && git pull'

workflows:
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: main

