version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:latest
      - image: circleci/python:3.9.6-buster
    steps:
      - checkout
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "${KEY_FINGERPRINT}"
      - run:
          name: Add github.com to known hosts
          command: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
      - run:
          name: SSH
          command: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${USER_NAME}@${HOST_NAME}

workflows:
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: main

