name: ci
on:
  push:
    branches:
      - master
      - main
      - gh-pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs build -d ./book/
      - run: mv ./book/* .
      - run: rm -rf ./book/
      - run: mkdocs gh-deploy --force
